/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author aluno
 */
public class ControlePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ControlePrincipal
     */
    public ControlePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        label1 = new java.awt.Label();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        desfazerSaidaVenda = new javax.swing.JButton();
        realizarVenda = new javax.swing.JButton();
        realizarSaida = new javax.swing.JButton();
        realizarLembretes = new javax.swing.JButton();
        verificarNotas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tabelaPrincipalEntrada = new javax.swing.JScrollPane();
        tabelaEntrada = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tabelaPrincipalSaida = new javax.swing.JScrollPane();
        tabelaSaida = new javax.swing.JTable();
        calendarioTela = new com.toedter.calendar.JCalendar();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewLembretesAmanha = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewLembretesHoje1 = new javax.swing.JTextArea();
        menuInterfacePrincipal = new javax.swing.JMenuBar();
        menuCaixa = new javax.swing.JMenu();
        fecharCaixa = new javax.swing.JMenuItem();
        abrirCaixa = new javax.swing.JMenuItem();
        desCompra = new javax.swing.JMenuItem();
        gerarExtrato = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        cadCliente = new javax.swing.JMenuItem();
        cadFuncionario = new javax.swing.JMenuItem();
        cadNota = new javax.swing.JMenuItem();
        menuVerificar = new javax.swing.JMenu();
        verCliente = new javax.swing.JMenuItem();
        verFuncionario = new javax.swing.JMenuItem();
        verNotas = new javax.swing.JMenuItem();
        menuVerificar1 = new javax.swing.JMenu();
        excluirCliente = new javax.swing.JMenuItem();
        excluirFuncionario = new javax.swing.JMenuItem();
        excluirNota = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        label1.setText("label1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 2, 22)); // NOI18N
        jButton3.setText("Verificar Notas");
        jButton3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Caixa Ternura Flores");
        setSize(new java.awt.Dimension(0, 0));

        desfazerSaidaVenda.setFont(new java.awt.Font("Comic Sans MS", 2, 22)); // NOI18N
        desfazerSaidaVenda.setText("Desfazer");
        desfazerSaidaVenda.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        desfazerSaidaVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desfazerSaidaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desfazerSaidaVendaActionPerformed(evt);
            }
        });

        realizarVenda.setFont(new java.awt.Font("Comic Sans MS", 2, 22)); // NOI18N
        realizarVenda.setText("Realizar Venda");
        realizarVenda.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        realizarVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        realizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVendaActionPerformed(evt);
            }
        });

        realizarSaida.setFont(new java.awt.Font("Comic Sans MS", 2, 22)); // NOI18N
        realizarSaida.setText("Realizar Saida");
        realizarSaida.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        realizarSaida.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        realizarSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarSaidaActionPerformed(evt);
            }
        });

        realizarLembretes.setFont(new java.awt.Font("Comic Sans MS", 2, 22)); // NOI18N
        realizarLembretes.setText("Lembretes");
        realizarLembretes.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        realizarLembretes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        realizarLembretes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarLembretesActionPerformed(evt);
            }
        });

        verificarNotas.setFont(new java.awt.Font("Comic Sans MS", 2, 22)); // NOI18N
        verificarNotas.setText("Verificar Notas");
        verificarNotas.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        verificarNotas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        verificarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarNotasActionPerformed(evt);
            }
        });

        tabelaEntrada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaEntrada.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tabelaEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Júnior Maritins", "1 - Ramalhete",  new Float(79.9)},
                {null, "", null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Descrição da Venda", "Total/Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaPrincipalEntrada.setViewportView(tabelaEntrada);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jLabel1.setText("Saída");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        jLabel2.setText("Vendas");

        tabelaSaida.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaSaida.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        tabelaSaida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Júnior Maritins", "Lanche", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Funcionario", "Descrição da Saida", "TotalSaida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaPrincipalSaida.setViewportView(tabelaSaida);
        if (tabelaSaida.getColumnModel().getColumnCount() > 0) {
            tabelaSaida.getColumnModel().getColumn(0).setPreferredWidth(2);
            tabelaSaida.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        calendarioTela.setBackground(new java.awt.Color(0, 153, 255));
        calendarioTela.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        viewLembretesAmanha.setBackground(new java.awt.Color(255, 255, 0));
        viewLembretesAmanha.setColumns(20);
        viewLembretesAmanha.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        viewLembretesAmanha.setRows(5);
        viewLembretesAmanha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lembretes Amanhã", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 3, 16))); // NOI18N
        jScrollPane1.setViewportView(viewLembretesAmanha);

        viewLembretesHoje1.setBackground(new java.awt.Color(255, 255, 0));
        viewLembretesHoje1.setColumns(20);
        viewLembretesHoje1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        viewLembretesHoje1.setRows(5);
        viewLembretesHoje1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lembretes Hoje", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 3, 16))); // NOI18N
        jScrollPane2.setViewportView(viewLembretesHoje1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelaPrincipalSaida)
                    .addComponent(tabelaPrincipalEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calendarioTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabelaPrincipalEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendarioTela, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(tabelaPrincipalSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

        menuInterfacePrincipal.setBackground(new java.awt.Color(204, 204, 204));
        menuInterfacePrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuInterfacePrincipal.setForeground(new java.awt.Color(255, 255, 255));
        menuInterfacePrincipal.setToolTipText("");
        menuInterfacePrincipal.setAlignmentX(2.0F);
        menuInterfacePrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuInterfacePrincipal.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        menuInterfacePrincipal.setInheritsPopupMenu(true);

        menuCaixa.setBackground(new java.awt.Color(153, 153, 153));
        menuCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/coins.png"))); // NOI18N
        menuCaixa.setText("Caixa          ");
        menuCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCaixa.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        menuCaixa.setHideActionText(true);

        fecharCaixa.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        fecharCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/coins.png"))); // NOI18N
        fecharCaixa.setText("Fechar Caixa");
        fecharCaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fecharCaixa.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                fecharCaixaMouseWheelMoved(evt);
            }
        });
        menuCaixa.add(fecharCaixa);

        abrirCaixa.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        abrirCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/coins_add.png"))); // NOI18N
        abrirCaixa.setText("Abrir Caixa");
        menuCaixa.add(abrirCaixa);

        desCompra.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        desCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/coins_delete.png"))); // NOI18N
        desCompra.setText("Desfazer Compra");
        desCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desCompraActionPerformed(evt);
            }
        });
        menuCaixa.add(desCompra);

        gerarExtrato.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        gerarExtrato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/coins.png"))); // NOI18N
        gerarExtrato.setText("Gerar Extrato");
        gerarExtrato.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        gerarExtrato.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                gerarExtratoMouseWheelMoved(evt);
            }
        });
        menuCaixa.add(gerarExtrato);

        menuInterfacePrincipal.add(menuCaixa);

        menuCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/group.png"))); // NOI18N
        menuCadastrar.setText("Cadastrar          ");
        menuCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuCadastrar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        cadCliente.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        cadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/group_add.png"))); // NOI18N
        cadCliente.setText("Cliente");
        menuCadastrar.add(cadCliente);

        cadFuncionario.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        cadFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/group_add.png"))); // NOI18N
        cadFuncionario.setText("Funcionario");
        cadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFuncionarioActionPerformed(evt);
            }
        });
        menuCadastrar.add(cadFuncionario);

        cadNota.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        cadNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/group_add.png"))); // NOI18N
        cadNota.setText("Nota");
        menuCadastrar.add(cadNota);

        menuInterfacePrincipal.add(menuCadastrar);

        menuVerificar.setBackground(new java.awt.Color(204, 204, 204));
        menuVerificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/book.png"))); // NOI18N
        menuVerificar.setText("Verificar          ");
        menuVerificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuVerificar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        verCliente.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        verCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/magnifier.png"))); // NOI18N
        verCliente.setText("Cliente");
        menuVerificar.add(verCliente);

        verFuncionario.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        verFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/magnifier.png"))); // NOI18N
        verFuncionario.setText("Funcionario");
        menuVerificar.add(verFuncionario);

        verNotas.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        verNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/magnifier.png"))); // NOI18N
        verNotas.setText("Notas");
        menuVerificar.add(verNotas);

        menuInterfacePrincipal.add(menuVerificar);

        menuVerificar1.setBackground(new java.awt.Color(204, 204, 204));
        menuVerificar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/cross.png"))); // NOI18N
        menuVerificar1.setText("Excluir          ");
        menuVerificar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuVerificar1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        excluirCliente.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        excluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/user_delete.png"))); // NOI18N
        excluirCliente.setText("Cliente");
        menuVerificar1.add(excluirCliente);

        excluirFuncionario.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        excluirFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/user_delete.png"))); // NOI18N
        excluirFuncionario.setText("Funcionário");
        menuVerificar1.add(excluirFuncionario);

        excluirNota.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        excluirNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons 1/user_delete.png"))); // NOI18N
        excluirNota.setText("Nota");
        menuVerificar1.add(excluirNota);

        menuInterfacePrincipal.add(menuVerificar1);

        setJMenuBar(menuInterfacePrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(realizarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addGap(58, 58, 58)
                        .addComponent(realizarSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addGap(59, 59, 59)
                        .addComponent(desfazerSaidaVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addGap(58, 58, 58)
                        .addComponent(verificarNotas, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addGap(59, 59, 59)
                        .addComponent(realizarLembretes, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(realizarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(realizarSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desfazerSaidaVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verificarNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(realizarLembretes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void desCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desCompraActionPerformed

    private void fecharCaixaMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_fecharCaixaMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_fecharCaixaMouseWheelMoved

    private void desfazerSaidaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desfazerSaidaVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desfazerSaidaVendaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void realizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realizarVendaActionPerformed

    private void realizarSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realizarSaidaActionPerformed

    private void realizarLembretesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarLembretesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realizarLembretesActionPerformed

    private void verificarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verificarNotasActionPerformed

    private void cadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadFuncionarioActionPerformed

    private void gerarExtratoMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_gerarExtratoMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_gerarExtratoMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirCaixa;
    private javax.swing.JMenuItem cadCliente;
    private javax.swing.JMenuItem cadFuncionario;
    private javax.swing.JMenuItem cadNota;
    private com.toedter.calendar.JCalendar calendarioTela;
    private javax.swing.JMenuItem desCompra;
    private javax.swing.JButton desfazerSaidaVenda;
    private javax.swing.JMenuItem excluirCliente;
    private javax.swing.JMenuItem excluirFuncionario;
    private javax.swing.JMenuItem excluirNota;
    private javax.swing.JMenuItem fecharCaixa;
    private javax.swing.JMenuItem gerarExtrato;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuCaixa;
    private javax.swing.JMenuBar menuInterfacePrincipal;
    private javax.swing.JMenu menuVerificar;
    private javax.swing.JMenu menuVerificar1;
    private javax.swing.JButton realizarLembretes;
    private javax.swing.JButton realizarSaida;
    private javax.swing.JButton realizarVenda;
    private javax.swing.JTable tabelaEntrada;
    private javax.swing.JScrollPane tabelaPrincipalEntrada;
    private javax.swing.JScrollPane tabelaPrincipalSaida;
    private javax.swing.JTable tabelaSaida;
    private javax.swing.JMenuItem verCliente;
    private javax.swing.JMenuItem verFuncionario;
    private javax.swing.JMenuItem verNotas;
    private javax.swing.JButton verificarNotas;
    private javax.swing.JTextArea viewLembretesAmanha;
    private javax.swing.JTextArea viewLembretesHoje1;
    // End of variables declaration//GEN-END:variables
}
